### ISSUE TITLE
Recursion depth limit

### ISSUE THREAD

**Issue by amine177** [Dainerx/mapper_i18n#2]
I think thinking about a way to remediate reaching the recursion depth limit is necessary here. 
https://github.com/Dainerx/mapper_i18n/blob/c16fcde6926cf5625247b866de920f2c90877b26/mapper.php#L97

**Comment by Dainerx** [comment]
Hey @amine177 that was a very good remark. I didn't pay much attention to the recursion depth cause run time wise it is O(|path|). The recursion greedily pick its tree path based on the path. So even in case the path goes up to 100 (which is outrageous) it wouldn't be a big problem. 

But now since you've mentioned I would give it more thought. 

What are your suggestions though? 

Thank you for taking time to give it a look.

**Comment by amine177** [comment]
I think one reasonable solution is to "peel" the nested levels.
Say we reached the recursion depth limit, we should return and parse the rest until we finish or reach the recursion depth and so on. 
I don't know if this would be feasible or practical especially after you mentioned that a path wouldn't mostly reach 100 ...
But if one would implement that solution, a function that parses until it reaches the limit is needed , than it should return the rest or an indication that it parsed all the input ..

**Comment by Dainerx** [comment]
I believe even though it looks unnecessary since practically speaking it wouldn't reach 100, writing a piece of code that prevents the reach of stack calls limit is a necessity. 

I'm not very familiar with peeling nested levels in recursion yet, I'll take a look at it and study the matter little further before introducing the changes. 

As for now I'll leave this issue open until I come with a solid fix. Please feel free to open any pull requests.

Cheers!

**Comment by amine177** [comment]
Well after some research it seems the php recursion limit is safe, in my machine it is in the order of 800k , so i assume there wouldn't exist a html file that goes to something more than 1000 levels of nesting ..
